[package]
name = "xmltree"
version = "0.6.0"
authors = ["Andrew Chin <achin@eminence32.net>"]
description = "Parse an XML file into a simple tree-like structure"
documentation = "http://eminence.github.io/xmltree-rs/doc/xmltree/index.html"
repository = "https://github.com/eminence/xmltree-rs"
keywords = ["xml", "parse", "xmltree"]
license = "MIT"
readme = "README.md"
categories = ["parsing", "data-structures"]


[dependencies]
xml-rs = "0.7"

